# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
# Set up pre-commit with pip install pre-commit; pre-commit install; pre-commit run --all-files
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: check-yaml
      - id: check-added-large-files
        #  - repo: https://github.com/google/yamlfmt
        #    rev: v0.14.0
        #    hooks:
        #      - id: yamlfmt
